version: '3'
services:
  web-app:
   image: node
   command:
        sh -c "cd app &&
             apt-get update &&
             apt-get install -y libgif-dev &&
             npm install  &&
             npm run serve"
   volumes:
    - ./cosmo-frontend/:/app/
    - /app/node_modules
   ports:
    - 8070:8070
  python-service:
   image: python:latest
   command:
      sh -c "cd app &&
             pip install -r requirements.txt &&
             python3 app.py"
   volumes:
    - ./cosmo-backend/python-server/app.py:/app/app.py
    - ./cosmo-backend/python-server/data/:/app/data/
    - ./cosmo-backend/python-server/requirements.txt:/app/requirements.txt
   ports:
    - 5500:5500
  r-service:
   image: rocker/r-base
   command:
        sh -c "cd /app/R-server &&
             apt-get update &&
             cat libraries-bin.txt | xargs apt-get install -y -qq &&
             Rscript libraries.R &&
             Rscript api-controller.R"
   volumes:
    - ./cosmo-backend/R-server/api-controller.R:/app/R-server/api-controller.R
    - ./cosmo-backend/R-server/libraries.R:/app/R-server/libraries.R
    - ./cosmo-backend/R-server/libraries-bin.txt:/app/R-server/libraries-bin.txt
    - ./cosmo-backend/R-server/data/:/app/R-server/data/
    - ./cosmo-backend/R-server/rscript/:/app/R-server/rscript/
   ports:
    - 5000:5000
  json-service:
   image: node:alpine    
   command:
      sh -c "cd app &&
             npm install  &&
             node json-server/server.js"
   volumes:
    - ./cosmo-backend/json-server/package.json:/app/package.json
    - ./cosmo-backend/json-server/json-server/:/app/json-server/
   ports:
    - 5300:5300